apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: oom-simulator
  name: oom-simulator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oom-simulator
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: oom-simulator
    spec:
      containers:
      - image: quay.io/naingyeminn/oom-simulator:1.0.1
        imagePullPolicy: Always
        name: oom-simulator
        env:
        - name: JAVA_OPTS
          value: " -XX:InitialRAMPercentage=25 -XX:MaxRAMPercentage=90 "
        - name: MEMORY_LIMIT
          value: "710"
        - name: MEMORY_INCREMENT
          value: "5"
        resources:
          limits:
            memory: 1024Mi
          requests:
            cpu: 100m
            memory: 1024Mi
